  export const keys = {
    a: {
      type: "me",
      text: "Full stack developer with over 2 years of experience, specializing in ReactJS, NodeJS, and others.",
      img: "",
    },
    b: { type: "background", text: "", img: "" },
    c: { type: "portfolio", text: "", img: "" },
    d: { type: "socials1", text: "", img: "" },
    e: { type: "socials2", text: "", img: "" },
    o: { type: "socials3", text: "", img: "" },
    f: { type: "socials4", text: "", img: "github" },
    g: { type: "socials5", text: "", img: "" },
    h: { type: "experience", text: "", img: "" },
    i: {
      type: "projects",
      id: "Pomodoro",
      images: "pomodoro.png",
      github: "https://github.com/1Optimus/Pomodoro",
      demo: "https://pomodoro-ecru-chi.vercel.app/",
    },
    j: {
      type: "projects",
      id: "Json to CSV",
      images: "jsontocsv.png",
      github: "https://github.com/1Optimus/jsontocsv",
      demo: "https://jsontocsv-1optimus.vercel.app/",
    },
    k: {
      type: "projects",
      id: "One Time Secret",
      images: "oneTimeSecret1.png",
      github: "https://github.com/1Optimus/onetimesecret",
      demo: "null",
    },
    l: {
      type: "projects",
      id: "Url shortener",
      images: "urlshortener.png",
      github: "https://github.com/1Optimus/urlshortener",
      demo: "null",
    },
    m: {
      type: "projects",
      id: "residential",
      images:"r1.png",
      github: "https://github.com/1Optimus/PG-Public",
      demo: "null",
    },
    n: {
      type: "projects",
      id: "Form",
      images: "form.png",
      github: "https://github.com/1Optimus/Form",
      demo: "https://form-woad-five.vercel.app/",
    },
    p: {
      type: "projects",
      id: "Gallery",
      images: "GCP.jpg",
      github: "https://github.com/1Optimus/GCP-project",
      demo: "null",
    },
    q: {
      type: "projects",
      id: "True Flavor",
      images: "Trueflavorimage.png",
      github: "https://github.com/1Optimus/trueFlavor",
      demo: "https://true-flavor.vercel.app/",
    },
    r: {
      type: "projects",
      id: "Pokedex",
      images: "Poke1.png",
      github: "https://github.com/1Optimus/Pokedex",
      demo: "null",
    },
  }; 

export const AboutLayout = {
    lg: [
      { i: "a", x: 1, y: 1, w: 2, h: 2, isResizable: false },
      { i: "b", x: 0, y: 0, w: 2, h: 0.5, isResizable: false },
      { i: "c", x: 3, y: 0, w: 1, h: 1, isResizable: false },
      { i: "d", x: 0, y: 1, w: 1, h: 1, isResizable: false },
      { i: "e", x: 2, y: 0, w: 2, h: 0.5, isResizable: false },
      { i: "f", x: 3, y: 1, w: 1, h: 1, isResizable: false },
      { i: "g", x: 0, y: 3, w: 2, h: 1, isResizable: false },
      { i: "h", x: 2, y: 3, w: 2, h: 2, isResizable: false },
      { i: "i", x: 0, y: 4, w: 2, h: 2, isResizable: false },
      { i: "j", x: 2, y: 6, w: 2, h: 2, isResizable: false },
      { i: "k", x: 0, y: 7, w: 2, h: 2, isResizable: false },
      { i: "l", x: 2, y: 6, w: 2, h: 2, isResizable: false },
      { i: "m", x: 0, y: 8, w: 2, h: 2, isResizable: false },
      { i: "n", x: 2, y: 9, w: 2, h: 2, isResizable: false },
      { i: "o", x: 0, y: 3, w: 1, h: 1, isResizable: false },
      { i: "p", x: 0, y: 10, w: 2, h: 2, isResizable: false },
      { i: "q", x: 2, y: 10, w: 2, h: 2, isResizable: false },
      { i: "r", x: 0, y: 12, w: 2, h: 2, isResizable: false },
    ],
    md: [
      { i: "a", x: 0, y: 0, w: 2, h: 2, isResizable: false },
      { i: "b", x: 2, y: 1, w: 2, h: 0.5, isResizable: false },
      { i: "c", x: 3, y: 0, w: 1, h: 1, isResizable: false },
      { i: "d", x: 2, y: 0, w: 1, h: 1, isResizable: false },
      { i: "e", x: 0, y: 2, w: 2, h: 0.5, isResizable: false },
      { i: "f", x: 3, y: 1, w: 1, h: 1, isResizable: false },
      { i: "g", x: 2, y: 3, w: 2, h: 1, isResizable: false },
      { i: "h", x: 2, y: 3, w: 2, h: 2, isResizable: false },
      { i: "i", x: 0, y: 4, w: 2, h: 2, isResizable: false },
      { i: "j", x: 2, y: 6, w: 2, h: 2, isResizable: false },
      { i: "k", x: 0, y: 7, w: 2, h: 2, isResizable: false },
      { i: "l", x: 2, y: 6, w: 2, h: 2, isResizable: false },
      { i: "m", x: 0, y: 8, w: 2, h: 2, isResizable: false },
      { i: "n", x: 2, y: 9, w: 2, h: 2, isResizable: false },
      { i: "o", x: 2, y: 3, w: 1, h: 1, isResizable: false },
      { i: "p", x: 0, y: 10, w: 2, h: 2, isResizable: false },
      { i: "q", x: 2, y: 10, w: 2, h: 2, isResizable: false },
      { i: "r", x: 0, y: 12, w: 2, h: 2, isResizable: false },
    ],
    xs: [
      { i: "a", x: 0, y: 0, w: 2, h: 2, isResizable: false },
      { i: "b", x: 1, y: 1, w: 2, h: 0.5, isResizable: false },
      { i: "c", x: 3, y: 0, w: 1, h: 1, isResizable: false },
      { i: "d", x: 0, y: 1, w: 1, h: 1, isResizable: false },
      { i: "e", x: 2, y: 0, w: 2, h: 1, isResizable: false },
      { i: "f", x: 3, y: 1, w: 1, h: 1, isResizable: false },
      { i: "g", x: 0, y: 3, w: 2, h: 1, isResizable: false },
      { i: "h", x: 2, y: 3, w: 2, h: 2, isResizable: false },
      { i: "i", x: 0, y: 4, w: 2, h: 2, isResizable: false },
      { i: "j", x: 2, y: 6, w: 2, h: 2, isResizable: false },
      { i: "k", x: 0, y: 7, w: 2, h: 2, isResizable: false },
      { i: "l", x: 2, y: 6, w: 2, h: 2, isResizable: false },
      { i: "m", x: 0, y: 8, w: 2, h: 2, isResizable: false },
      { i: "n", x: 2, y: 9, w: 2, h: 2, isResizable: false },
      { i: "o", x: 0, y: 3, w: 1, h: 1, isResizable: false },
      { i: "p", x: 0, y: 10, w: 2, h: 2, isResizable: false },
      { i: "q", x: 2, y: 10, w: 2, h: 2, isResizable: false },
      { i: "r", x: 0, y: 12, w: 2, h: 2, isResizable: false },
    ],
  };



 export const ProjectsLayouts = {
    lg: [
      { i: "a", x: 4, y: 12, w: 2, h: 2, isResizable: false },
      { i: "b", x: 0, y: 1, w: 2, h: 0.5, isResizable: false },
      { i: "c", x: 3, y: 1, w: 1, h: 1, isResizable: false },
      { i: "d", x: 2, y: 10, w: 1, h: 1, isResizable: false },
      { i: "e", x: 2, y: 0, w: 2, h: 0.5, isResizable: false },
      { i: "f", x: 2, y: 1, w: 1, h: 1, isResizable: false },
      { i: "g", x: 4, y: 11, w: 2, h: 1, isResizable: false },
      { i: "h", x: 0, y: 2, w: 2, h: 2, isResizable: false },
      { i: "i", x: 0, y: 3, w: 2, h: 2, isResizable: false },
      { i: "j", x: 2, y: 2, w: 2, h: 2, isResizable: false },
      { i: "k", x: 0, y: 5, w: 2, h: 2, isResizable: false },
      { i: "l", x: 2, y: 4, w: 2, h: 2, isResizable: false },
      { i: "m", x: 0, y: 7, w: 2, h: 2, isResizable: false },
      { i: "n", x: 2, y: 6, w: 2, h: 2, isResizable: false },
      { i: "o", x: 4, y: 10, w: 1, h: 1, isResizable: false },
      { i: "p", x: 0, y: 9, w: 2, h: 2, isResizable: false },
      { i: "q", x: 2, y: 8, w: 2, h: 2, isResizable: false },
      { i: "r", x: 0, y: 12, w: 2, h: 2, isResizable: false },
    ],
    md: [
      { i: "a", x: 4, y: 12, w: 2, h: 2, isResizable: false },
      { i: "b", x: 0, y: 1, w: 2, h: 0.5, isResizable: false },
      { i: "c", x: 3, y: 1, w: 1, h: 1, isResizable: false },
      { i: "d", x: 2, y: 10, w: 1, h: 1, isResizable: false },
      { i: "e", x: 2, y: 3, w: 2, h: 0.5, isResizable: false },
      { i: "f", x: 2, y: 1, w: 1, h: 1, isResizable: false },
      { i: "g", x: 4, y: 11, w: 2, h: 1, isResizable: false },
      { i: "h", x: 0, y: 2, w: 2, h: 2, isResizable: false },
      { i: "i", x: 0, y: 3, w: 2, h: 2, isResizable: false },
      { i: "j", x: 2, y: 2, w: 2, h: 2, isResizable: false },
      { i: "k", x: 0, y: 5, w: 2, h: 2, isResizable: false },
      { i: "l", x: 2, y: 4, w: 2, h: 2, isResizable: false },
      { i: "m", x: 0, y: 7, w: 2, h: 2, isResizable: false },
      { i: "n", x: 2, y: 6, w: 2, h: 2, isResizable: false },
      { i: "o", x: 4, y: 10, w: 1, h: 1, isResizable: false },
      { i: "p", x: 0, y: 9, w: 2, h: 2, isResizable: false },
      { i: "q", x: 2, y: 8, w: 2, h: 2, isResizable: false },
      { i: "r", x: 0, y: 12, w: 2, h: 2, isResizable: false },
    ],
    xs: [
      { i: "a", x: 4, y: 12, w: 2, h: 2, isResizable: false },
      { i: "b", x: 0, y: 1, w: 2, h: 0.5, isResizable: false },
      { i: "c", x: 3, y: 1, w: 1, h: 1, isResizable: false },
      { i: "d", x: 2, y: 10, w: 1, h: 1, isResizable: false },
      { i: "e", x: 2, y: 0, w: 2, h: 1, isResizable: false },
      { i: "f", x: 2, y: 1, w: 1, h: 1, isResizable: false },
      { i: "g", x: 4, y: 11, w: 2, h: 1, isResizable: false },
      { i: "h", x: 0, y: 2, w: 2, h: 2, isResizable: false },
      { i: "i", x: 0, y: 3, w: 2, h: 2, isResizable: false },
      { i: "j", x: 2, y: 2, w: 2, h: 2, isResizable: false },
      { i: "k", x: 0, y: 5, w: 2, h: 2, isResizable: false },
      { i: "l", x: 2, y: 4, w: 2, h: 2, isResizable: false },
      { i: "m", x: 0, y: 7, w: 2, h: 2, isResizable: false },
      { i: "n", x: 2, y: 6, w: 2, h: 2, isResizable: false },
      { i: "o", x: 4, y: 10, w: 1, h: 1, isResizable: false },
      { i: "p", x: 0, y: 9, w: 2, h: 2, isResizable: false },
      { i: "q", x: 2, y: 8, w: 2, h: 2, isResizable: false },
      { i: "r", x: 0, y: 12, w: 2, h: 2, isResizable: false },
    ],
  };


  
  export const ContactLayouts = {
    lg: [
      { i: "a", x: 0, y: 0, w: 2, h: 2, isResizable: false },
      { i: "b", x: 0, y: 2, w: 2, h: 0.5, isResizable: false },
      { i: "c", x: 2, y: 0, w: 1, h: 1, isResizable: false },
      { i: "d", x: 2, y: 0, w: 1, h: 1, isResizable: false },
      { i: "e", x: 2, y: 2, w: 2, h: 0.5, isResizable: false },
      { i: "f", x: 3, y: 1, w: 1, h: 1, isResizable: false },
      { i: "g", x: 2, y: 1, w: 2, h: 1, isResizable: false },
      { i: "h", x: 2, y: 3, w: 2, h: 2, isResizable: false },
      { i: "i", x: 0, y: 4, w: 2, h: 2, isResizable: false },
      { i: "j", x: 2, y: 6, w: 2, h: 2, isResizable: false },
      { i: "k", x: 0, y: 7, w: 2, h: 2, isResizable: false },
      { i: "l", x: 2, y: 6, w: 2, h: 2, isResizable: false },
      { i: "m", x: 0, y: 8, w: 2, h: 2, isResizable: false },
      { i: "n", x: 2, y: 9, w: 2, h: 2, isResizable: false },
      { i: "o", x: 4, y: 1, w: 1, h: 1, isResizable: false },
      { i: "p", x: 0, y: 10, w: 2, h: 2, isResizable: false },
      { i: "q", x: 2, y: 10, w: 2, h: 2, isResizable: false },
      { i: "r", x: 0, y: 12, w: 2, h: 2, isResizable: false },
    ],
    md: [
      { i: "a", x: 0, y: 0, w: 2, h: 2, isResizable: false },
      { i: "b", x: 0, y: 2, w: 2, h: 0.5, isResizable: false },
      { i: "c", x: 2, y: 0, w: 1, h: 1, isResizable: false },
      { i: "d", x: 2, y: 0, w: 1, h: 1, isResizable: false },
      { i: "e", x: 2, y: 2, w: 2, h: 0.5, isResizable: false },
      { i: "f", x: 3, y: 1, w: 1, h: 1, isResizable: false },
      { i: "g", x: 2, y: 1, w: 2, h: 1, isResizable: false },
      { i: "h", x: 2, y: 3, w: 2, h: 2, isResizable: false },
      { i: "i", x: 0, y: 4, w: 2, h: 2, isResizable: false },
      { i: "j", x: 2, y: 6, w: 2, h: 2, isResizable: false },
      { i: "k", x: 0, y: 7, w: 2, h: 2, isResizable: false },
      { i: "l", x: 2, y: 6, w: 2, h: 2, isResizable: false },
      { i: "m", x: 0, y: 8, w: 2, h: 2, isResizable: false },
      { i: "n", x: 2, y: 9, w: 2, h: 2, isResizable: false },
      { i: "o", x: 4, y: 1, w: 1, h: 1, isResizable: false },
      { i: "p", x: 0, y: 10, w: 2, h: 2, isResizable: false },
      { i: "q", x: 2, y: 10, w: 2, h: 2, isResizable: false },
      { i: "r", x: 0, y: 12, w: 2, h: 2, isResizable: false },
    ],
    xs: [
      { i: "a", x: 0, y: 0, w: 2, h: 2, isResizable: false },
      { i: "b", x: 0, y: 2, w: 2, h: 0.5, isResizable: false },
      { i: "c", x: 2, y: 0, w: 1, h: 1, isResizable: false },
      { i: "d", x: 2, y: 0, w: 1, h: 1, isResizable: false },
      { i: "e", x: 2, y: 2, w: 2, h: 0.5, isResizable: false },
      { i: "f", x: 3, y: 1, w: 1, h: 1, isResizable: false },
      { i: "g", x: 2, y: 1, w: 2, h: 1, isResizable: false },
      { i: "h", x: 2, y: 3, w: 2, h: 2, isResizable: false },
      { i: "i", x: 0, y: 4, w: 2, h: 2, isResizable: false },
      { i: "j", x: 2, y: 6, w: 2, h: 2, isResizable: false },
      { i: "k", x: 0, y: 7, w: 2, h: 2, isResizable: false },
      { i: "l", x: 2, y: 6, w: 2, h: 2, isResizable: false },
      { i: "m", x: 0, y: 8, w: 2, h: 2, isResizable: false },
      { i: "n", x: 2, y: 9, w: 2, h: 2, isResizable: false },
      { i: "o", x: 4, y: 1, w: 1, h: 1, isResizable: false },
      { i: "p", x: 0, y: 10, w: 2, h: 2, isResizable: false },
      { i: "q", x: 2, y: 10, w: 2, h: 2, isResizable: false },
      { i: "r", x: 0, y: 12, w: 2, h: 2, isResizable: false },
    ],
  };

