export const keys = {
  a: {
    type: "me",
    text: "Full stack developer with over 2 years of experience, specializing in ReactJS, NodeJS, and others.",
    img: "me2.png",
  },
  b: { type: "background", text: "", img: "" },
  c: { type: "portfolio", text: "", img: "" },
  d: {
    type: "socials",
    text: "linkedin",
    img: "linkedin.json",
    demo: "https://jsontocsv-1optimus.vercel.app/",
  },
  e: {
    type: "socials",
    text: "mail",
    img: "mail.json",
    demo: "https://jsontocsv-1optimus.vercel.app/",
  },
  o: {
    type: "socials",
    text: "github",
    img: "gith.json",
    demo: "https://jsontocsv-1optimus.vercel.app/",
  },
  f: { type: "socials", text: "github", img: "gith.json",demo: "https://jsontocsv-1optimus.vercel.app/", },
  g: { type: "socials", text: "github", img: "gith.json", demo: "https://jsontocsv-1optimus.vercel.app/", },
  h: { type: "experience", text: "Katoen Natie/IT Support & Analyst/Nov 2023-current job.TELUS international/ Full Stack ReactJS & NodeJS Developer/Guatemala Jan 2022 - Jul 2022.Greystone/Full stack ReactJS & Firebase/Jan 2021 - Nov 2021", img: "" },
  i: {
    type: "projects",
    id: "Pomodoro",
    images: "pomodoro.png",
    github: "https://github.com/1Optimus/Pomodoro",
    demo: "https://pomodoro-ecru-chi.vercel.app/",
    techno: "React.Javascript.CSS.TailwindCSS.Front-end",
  },
  j: {
    type: "projects",
    id: "Json to CSV",
    images: "jsontocsv.png",
    github: "https://github.com/1Optimus/jsontocsv",
    demo: "https://jsontocsv-1optimus.vercel.app/",
    techno: "React.Javascript.CSS.TailwindCSS.Front-end",
  },
  k: {
    type: "projects",
    id: "One Time Secret",
    images: "oneTimeSecret1.png",
    github: "https://github.com/1Optimus/onetimesecret",
    demo: "null",
    techno: "React.Javascript.CSS.TailwindCSS.Front-end",
  },
  l: {
    type: "projects",
    id: "Url shortener",
    images: "urlshortener.png",
    github: "https://github.com/1Optimus/urlshortener",
    demo: "null",
    techno: "React.Javascript.CSS.TailwindCSS.Front-end",
  },
  m: {
    type: "projects",
    id: "Property Management app",
    images: "r1.png",
    github: "https://github.com/1Optimus/PG-Public",
    demo: "null",
    techno: "React.Javascript.CSS.TailwindCSS.Front-end",
  },
  n: {
    type: "projects",
    id: "Form",
    images: "form.png",
    github: "https://github.com/1Optimus/Form",
    demo: "https://form-woad-five.vercel.app/",
    techno: "React.Javascript.CSS.TailwindCSS.Front-end",
  },
  p: {
    type: "projects",
    id: "Gallery",
    images: "GCP.jpg",
    github: "https://github.com/1Optimus/GCP-project",
    demo: "null",
    techno: "React.Javascript.CSS.TailwindCSS.Front-end",
  },
  q: {
    type: "projects",
    id: "True Flavor",
    images: "Trueflavorimage.png",
    github: "https://github.com/1Optimus/trueFlavor",
    demo: "https://true-flavor.vercel.app/",
    techno: "React.Javascript.CSS.TailwindCSS.Front-end",
  },
  r: {
    type: "projects",
    id: "Pokedex",
    images: "Poke4.png",
    github: "https://github.com/1Optimus/Pokedex",
    demo: "null",
    techno: "React.Javascript.CSS.TailwindCSS.Front-end",
  },
};

export const AboutLayout = {
  lg: [
    { i: "a", x: 0, y: 0, w: 4, h: 3, isResizable: false },
    { i: "b", x: 4, y: 0, w: 2, h: 1, isResizable: false },
    { i: "c", x: 4, y: 1, w: 3, h: 1, isResizable: false },
    { i: "d", x: 6, y: 0, w: 1, h: 1, isResizable: false },
    { i: "e", x: 4, y: 1, w: 1, h: 1, isResizable: false },
    { i: "f", x: 7, y: 3, w: 1, h: 1, isResizable: false },
    { i: "g", x: 0, y: 3, w: 6, h: 1, isResizable: false },
    { i: "h", x: 6, y: 4, w: 4, h: 2.5, isResizable: false },
    { i: "i", x: 0, y: 5, w: 4, h: 2.7, isResizable: false },
    { i: "j", x: 0, y: 8, w: 4, h: 2.7, isResizable: false },
    { i: "k", x: 4, y: 11, w: 4, h: 2.5, isResizable: false },
    { i: "l", x: 4, y: 14, w: 4, h: 2.5, isResizable: false },
    { i: "m", x: 0, y: 17, w: 4, h: 2.5, isResizable: false },
    { i: "n", x: 4, y: 20, w: 4, h: 2.7, isResizable: false },
    { i: "o", x: 7, y: 0, w: 1, h: 1, isResizable: false },
    { i: "p", x: 0, y: 23, w: 4, h: 2.7, isResizable: false },
    { i: "q", x: 0, y: 26, w: 4, h: 2.7, isResizable: false },
    { i: "r", x: 4, y: 23, w: 4, h: 3, isResizable: false },
  ],
  md: [
    { i: "a", x: 0, y: 0, w: 2, h: 2, isResizable: false },
    { i: "b", x: 2, y: 1, w: 2, h: 0.5, isResizable: false },
    { i: "c", x: 3, y: 0, w: 1, h: 1, isResizable: false },
    { i: "d", x: 2, y: 0, w: 1, h: 1, isResizable: false },
    { i: "e", x: 0, y: 2, w: 2, h: 0.5, isResizable: false },
    { i: "f", x: 3, y: 1, w: 1, h: 1, isResizable: false },
    { i: "g", x: 2, y: 3, w: 2, h: 1, isResizable: false },
    { i: "h", x: 2, y: 3, w: 2, h: 2, isResizable: false },
    { i: "i", x: 0, y: 4, w: 2, h: 2, isResizable: false },
    { i: "j", x: 2, y: 6, w: 2, h: 2, isResizable: false },
    { i: "k", x: 0, y: 7, w: 2, h: 2, isResizable: false },
    { i: "l", x: 2, y: 6, w: 2, h: 2, isResizable: false },
    { i: "m", x: 0, y: 8, w: 2, h: 2, isResizable: false },
    { i: "n", x: 2, y: 9, w: 2, h: 2, isResizable: false },
    { i: "o", x: 2, y: 3, w: 1, h: 1, isResizable: false },
    { i: "p", x: 0, y: 10, w: 2, h: 2, isResizable: false },
    { i: "q", x: 2, y: 10, w: 2, h: 2, isResizable: false },
    { i: "r", x: 0, y: 12, w: 2, h: 2, isResizable: false },
  ],
  xs: [
    { i: "a", x: 0, y: 0, w: 2, h: 2, isResizable: false },
    { i: "b", x: 1, y: 1, w: 2, h: 0.5, isResizable: false },
    { i: "c", x: 3, y: 0, w: 1, h: 1, isResizable: false },
    { i: "d", x: 0, y: 1, w: 1, h: 1, isResizable: false },
    { i: "e", x: 2, y: 0, w: 2, h: 1, isResizable: false },
    { i: "f", x: 3, y: 1, w: 1, h: 1, isResizable: false },
    { i: "g", x: 0, y: 3, w: 2, h: 1, isResizable: false },
    { i: "h", x: 2, y: 3, w: 2, h: 2, isResizable: false },
    { i: "i", x: 0, y: 4, w: 2, h: 2, isResizable: false },
    { i: "j", x: 2, y: 6, w: 2, h: 2, isResizable: false },
    { i: "k", x: 0, y: 7, w: 2, h: 2, isResizable: false },
    { i: "l", x: 2, y: 6, w: 2, h: 2, isResizable: false },
    { i: "m", x: 0, y: 8, w: 2, h: 2, isResizable: false },
    { i: "n", x: 2, y: 9, w: 2, h: 2, isResizable: false },
    { i: "o", x: 0, y: 3, w: 1, h: 1, isResizable: false },
    { i: "p", x: 0, y: 10, w: 2, h: 2, isResizable: false },
    { i: "q", x: 2, y: 10, w: 2, h: 2, isResizable: false },
    { i: "r", x: 0, y: 12, w: 2, h: 2, isResizable: false },
  ],
};

export const ProjectsLayouts = {
  lg: [
    { i: "a", x: 0, y: 0, w: 4, h: 3, isResizable: false },
    { i: "b", x: 4, y: 0, w: 2, h: 1, isResizable: false },
    { i: "c", x: 4, y: 1, w: 4, h: 1, isResizable: false },
    { i: "d", x: 6, y: 0, w: 1, h: 1, isResizable: false },
    { i: "e", x: 4, y: 1, w: 3, h: 1, isResizable: false },
    { i: "f", x: 7, y: 3, w: 1, h: 1, isResizable: false },
    { i: "g", x: 0, y: 3, w: 5, h: 1, isResizable: false },
    { i: "h", x: 6, y: 4, w: 3, h: 2, isResizable: false },
    { i: "i", x: 0, y: 5, w: 4, h: 3, isResizable: false },
    { i: "j", x: 0, y: 8, w: 4, h: 3, isResizable: false },
    { i: "k", x: 4, y: 11, w: 4, h: 3, isResizable: false },
    { i: "l", x: 4, y: 14, w: 4, h: 3, isResizable: false },
    { i: "m", x: 0, y: 17, w: 4, h: 3, isResizable: false },
    { i: "n", x: 4, y: 20, w: 4, h: 3, isResizable: false },
    { i: "o", x: 7, y: 0, w: 1, h: 1, isResizable: false },
    { i: "p", x: 0, y: 23, w: 4, h: 3, isResizable: false },
    { i: "q", x: 0, y: 26, w: 4, h: 3, isResizable: false },
    { i: "r", x: 4, y: 23, w: 4, h: 3, isResizable: false },
  ],
  md: [
    { i: "a", x: 4, y: 12, w: 2, h: 2, isResizable: false },
    { i: "b", x: 0, y: 1, w: 2, h: 0.5, isResizable: false },
    { i: "c", x: 3, y: 1, w: 1, h: 1, isResizable: false },
    { i: "d", x: 2, y: 10, w: 1, h: 1, isResizable: false },
    { i: "e", x: 2, y: 3, w: 2, h: 0.5, isResizable: false },
    { i: "f", x: 2, y: 1, w: 1, h: 1, isResizable: false },
    { i: "g", x: 4, y: 11, w: 2, h: 1, isResizable: false },
    { i: "h", x: 0, y: 2, w: 2, h: 2, isResizable: false },
    { i: "i", x: 0, y: 3, w: 2, h: 2, isResizable: false },
    { i: "j", x: 2, y: 2, w: 2, h: 2, isResizable: false },
    { i: "k", x: 0, y: 5, w: 2, h: 2, isResizable: false },
    { i: "l", x: 2, y: 4, w: 2, h: 2, isResizable: false },
    { i: "m", x: 0, y: 7, w: 2, h: 2, isResizable: false },
    { i: "n", x: 2, y: 6, w: 2, h: 2, isResizable: false },
    { i: "o", x: 4, y: 10, w: 1, h: 1, isResizable: false },
    { i: "p", x: 0, y: 9, w: 2, h: 2, isResizable: false },
    { i: "q", x: 2, y: 8, w: 2, h: 2, isResizable: false },
    { i: "r", x: 0, y: 12, w: 2, h: 2, isResizable: false },
  ],
  xs: [
    { i: "a", x: 4, y: 12, w: 2, h: 2, isResizable: false },
    { i: "b", x: 0, y: 1, w: 2, h: 0.5, isResizable: false },
    { i: "c", x: 3, y: 1, w: 1, h: 1, isResizable: false },
    { i: "d", x: 2, y: 10, w: 1, h: 1, isResizable: false },
    { i: "e", x: 2, y: 0, w: 2, h: 1, isResizable: false },
    { i: "f", x: 2, y: 1, w: 1, h: 1, isResizable: false },
    { i: "g", x: 4, y: 11, w: 2, h: 1, isResizable: false },
    { i: "h", x: 0, y: 2, w: 2, h: 2, isResizable: false },
    { i: "i", x: 0, y: 3, w: 2, h: 2, isResizable: false },
    { i: "j", x: 2, y: 2, w: 2, h: 2, isResizable: false },
    { i: "k", x: 0, y: 5, w: 2, h: 2, isResizable: false },
    { i: "l", x: 2, y: 4, w: 2, h: 2, isResizable: false },
    { i: "m", x: 0, y: 7, w: 2, h: 2, isResizable: false },
    { i: "n", x: 2, y: 6, w: 2, h: 2, isResizable: false },
    { i: "o", x: 4, y: 10, w: 1, h: 1, isResizable: false },
    { i: "p", x: 0, y: 9, w: 2, h: 2, isResizable: false },
    { i: "q", x: 2, y: 8, w: 2, h: 2, isResizable: false },
    { i: "r", x: 0, y: 12, w: 2, h: 2, isResizable: false },
  ],
};

export const ContactLayouts = {
  lg: [
    { i: "a", x: 0, y: 0, w: 4, h: 3, isResizable: false },
    { i: "b", x: 4, y: 0, w: 2, h: 1, isResizable: false },
    { i: "c", x: 4, y: 1, w: 4, h: 1, isResizable: false },
    { i: "d", x: 6, y: 0, w: 1, h: 1, isResizable: false },
    { i: "e", x: 4, y: 1, w: 3, h: 1, isResizable: false },
    { i: "f", x: 7, y: 3, w: 1, h: 1, isResizable: false },
    { i: "g", x: 0, y: 3, w: 5, h: 1, isResizable: false },
    { i: "h", x: 6, y: 4, w: 3, h: 2, isResizable: false },
    { i: "i", x: 0, y: 5, w: 4, h: 3, isResizable: false },
    { i: "j", x: 0, y: 8, w: 4, h: 3, isResizable: false },
    { i: "k", x: 4, y: 11, w: 4, h: 3, isResizable: false },
    { i: "l", x: 4, y: 14, w: 4, h: 3, isResizable: false },
    { i: "m", x: 0, y: 17, w: 4, h: 3, isResizable: false },
    { i: "n", x: 4, y: 20, w: 4, h: 3, isResizable: false },
    { i: "o", x: 7, y: 0, w: 1, h: 1, isResizable: false },
    { i: "p", x: 0, y: 23, w: 4, h: 3, isResizable: false },
    { i: "q", x: 0, y: 26, w: 4, h: 3, isResizable: false },
    { i: "r", x: 4, y: 23, w: 4, h: 3, isResizable: false },
  ],
  md: [
    { i: "a", x: 0, y: 0, w: 2, h: 2, isResizable: false },
    { i: "b", x: 0, y: 2, w: 2, h: 0.5, isResizable: false },
    { i: "c", x: 2, y: 0, w: 1, h: 1, isResizable: false },
    { i: "d", x: 2, y: 0, w: 1, h: 1, isResizable: false },
    { i: "e", x: 2, y: 2, w: 2, h: 0.5, isResizable: false },
    { i: "f", x: 3, y: 1, w: 1, h: 1, isResizable: false },
    { i: "g", x: 2, y: 1, w: 2, h: 1, isResizable: false },
    { i: "h", x: 2, y: 3, w: 2, h: 2, isResizable: false },
    { i: "i", x: 0, y: 4, w: 2, h: 2, isResizable: false },
    { i: "j", x: 2, y: 6, w: 2, h: 2, isResizable: false },
    { i: "k", x: 0, y: 7, w: 2, h: 2, isResizable: false },
    { i: "l", x: 2, y: 6, w: 2, h: 2, isResizable: false },
    { i: "m", x: 0, y: 8, w: 2, h: 2, isResizable: false },
    { i: "n", x: 2, y: 9, w: 2, h: 2, isResizable: false },
    { i: "o", x: 4, y: 1, w: 1, h: 1, isResizable: false },
    { i: "p", x: 0, y: 10, w: 2, h: 2, isResizable: false },
    { i: "q", x: 2, y: 10, w: 2, h: 2, isResizable: false },
    { i: "r", x: 0, y: 12, w: 2, h: 2, isResizable: false },
  ],
  xs: [
    { i: "a", x: 0, y: 0, w: 2, h: 2, isResizable: false },
    { i: "b", x: 0, y: 2, w: 2, h: 0.5, isResizable: false },
    { i: "c", x: 2, y: 0, w: 1, h: 1, isResizable: false },
    { i: "d", x: 2, y: 0, w: 1, h: 1, isResizable: false },
    { i: "e", x: 2, y: 2, w: 2, h: 0.5, isResizable: false },
    { i: "f", x: 3, y: 1, w: 1, h: 1, isResizable: false },
    { i: "g", x: 2, y: 1, w: 2, h: 1, isResizable: false },
    { i: "h", x: 2, y: 3, w: 2, h: 2, isResizable: false },
    { i: "i", x: 0, y: 4, w: 2, h: 2, isResizable: false },
    { i: "j", x: 2, y: 6, w: 2, h: 2, isResizable: false },
    { i: "k", x: 0, y: 7, w: 2, h: 2, isResizable: false },
    { i: "l", x: 2, y: 6, w: 2, h: 2, isResizable: false },
    { i: "m", x: 0, y: 8, w: 2, h: 2, isResizable: false },
    { i: "n", x: 2, y: 9, w: 2, h: 2, isResizable: false },
    { i: "o", x: 4, y: 1, w: 1, h: 1, isResizable: false },
    { i: "p", x: 0, y: 10, w: 2, h: 2, isResizable: false },
    { i: "q", x: 2, y: 10, w: 2, h: 2, isResizable: false },
    { i: "r", x: 0, y: 12, w: 2, h: 2, isResizable: false },
  ],
};
